---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          path: jq-emojify-${{github.ref_name}}
      - name: Build
        run: |
          wget -o- \
            https://raw.githubusercontent.com/github/gemoji/refs/heads/master/db/emoji.json
          tar vcafC ../jq-emojify-${{github.ref_name}}.tar.gz \
            jq-emojify-${{github.ref_name}} ..
          mv ../jq-emojify-${{github.ref_name}}.tar.gz .
      - uses: yuezk/publish-ppa-package@main
        with:
          repository: freedwu/ppa
          gpg_private_key: ${{secrets.GPG_PRIVATE_KEY}}
          gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
          tarball: ./*.tar.*
          deb_email: ${{secrets.DEB_EMAIL}}
          deb_fullname: freedwu
