---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          n="jq-emojify-$GITHUB_REF_NAME"
          cd ..
          mv jq-emojify "$n"
          tar vcaf ./"$n".tar.gz "$n"
          mv ./*.tar.* "$n"
          mv "$n" jq-emojify
      - uses: yuezk/publish-ppa-package@main
        with:
          repository: freedwu/ppa
          gpg_private_key: ${{secrets.GPG_PRIVATE_KEY}}
          gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
          tarball: ./*.tar.*
          deb_email: ${{secrets.DEB_EMAIL}}
          deb_fullname: freedwu
